spring.datasource.url=jdbc:postgresql://localhost:5432/rosetta
spring.datasource.username=postgres
spring.datasource.password=password1107
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

server.port = 1107

logging.file.name = rosetta.log
logging.file.max-size=1MB
logging.file.max-history=10